#!/bin/csh -f

set lines=`wc -l < smaz_corpus1.txt`

@ i = 1
echo "     raw  stats3  gzip-9   bzip2     paq"
while ($i <= $lines)
  head -${i} smaz_corpus1.txt | tail -1 > line.txt
  echo -n `wc -c < line.txt`
  echo -n ";"
  echo -n `head -${i} smaz_corpus1.txt | tail -1 | ./method_stats3 - | grep "compressed bytes" | head -1 | cut -f2 -d:`
  echo -n ";"
  echo -n `cat line.txt | gzip -9 - | wc -c `
  echo -n ";"
  echo -n `cat line.txt | bzip2 -9 - | wc -c `
  echo -n ";"
  echo -n `paq/paq8l line.txt</dev/null | tail -5 | head -1 | cut -f2 -d">"`
  echo ""
  @ i += 1
end
